#!/bin/sh

echo ""
echo "----------------------"
echo "Installing Homebrew"
echo "----------------------"
echo ""

curl -fsSkL raw.github.com/mxcl/homebrew/go | ruby
brew doctor

echo ""
echo "Installing packages..."

brew update
brew install ack ctags git git-extras hub rbenv ruby-build node zsh fasd python rename

# install required python libraries
easy_install pygments
ln -s /usr/local/share/python/pygmentize /usr/local/bin/
git clone https://github.com/gthank/solarized-dark-pygments.git $PWD/temp
cp $PWD/temp/solarized.py /usr/local/lib/python2.7/site-packages/pygments/styles/
rm -rf $PWD/temp

echo ""
echo "----------------------"
echo "Installing Prezto"
echo "----------------------"
echo ""

echo ""
echo "Cloning repo..."

git clone --recursive https://github.com/sorin-ionescu/prezto.git ~/.zprezto

echo ""
echo "Copy/link Zsh config files..."

ln -s $PWD/zshenv ~/.zshenv
ln -s $PWD/zshrc ~/.zshrc
ln -s $PWD/zpreztorc ~/.zpreztorc
ln -s ~/.zprezto/runcoms/zlogin ~/.zlogin
ln -s ~/.zprezto/runcoms/zlogout ~/.zlogout

echo ""
echo "Set Zsh as your default shell..."

sudo echo "/usr/local/bin/zsh" >> /etc/shells
chsh -s /usr/local/bin/zsh

echo ""
echo "Fixing pathing problems..."

sudo chmod ugo-x /usr/libexec/path_helper
sudo mv /etc/zshenv /etc/zprofile

echo ""
echo "----------------"
echo "Configuring Vim"
echo "----------------"
echo ""

ln -s $PWD/vimrc ~/.vimrc
ln -s $PWD/vim ~/.vim

echo ""
echo "Installing plugins..."
git clone https://github.com/gmarik/vundle.git $PWD/vim/bundle/vundle
vim -u ~/.dotfiles/vimrc.bundles +BundleInstall! +BundleClean +qall

echo ""
echo "----------------"
echo "Configuring Git"
echo "----------------"
echo ""

ln -s $PWD/gitconfig ~/.gitconfig
ln -s $PWD/gitignore ~/.gitignore

echo ""
echo "----------------"
echo "Wrap-up"
echo "----------------"
echo ""

echo ""
echo "Touching .secrets, don't forget to populate it"

touch ~/.secrets

echo ""
echo "...last but not least, installing fonts for vim statusline"

cd $PWD/fonts && for f in * ; do cp $f ~/Library/Fonts/$f ; done

echo ""
echo "DONE!"
